In [64]:
import numpy as np
import pandas as pd
import os

In [65]:
# Get raw data
def get_raw_data(path):
    df = pd.read_excel(path)
    #print(df.head(3))
    return df

In [66]:
# Load data
raw_data = get_raw_data('../data/raw_data/cascaded_use_case_data.xlsx')

In [67]:
# Review the data
raw_data.describe()

,Vindhastighet Nilsebu,Lufttemp. Nilsebu,Vindretning Nilsebu,RelHum Nilsebu,Vannstand Lyngsåna,Vanntemp. Hiafossen,Vannstand Hiafossen,Lufttemp Fister,Nedbør Fister,Q_Lyngsvatn_overlop,...,SNOW_MELT_HBV,SNOW_SWE_HBV,Evap_HBV,SOIL_WAT_HBV,GR_WAT_HBV,Q_Kalltveit_uten_tapping,Q_HBV_mean,Q_Lyngsaana,Vanntemp. Lyngsåna,Vanntemp. Kalltveit elv
count,62955.000000,63102.000000,63079.000000,63079.000000,50380.000000,50192.000000,50192.000000,63288.000000,63288.000000,63286.000000,...,29595.000000,29595.000000,29595.000000,29595.000000,29595.000000,63288.000000,31241.000000,63288.000000,63283.000000,50316.000000
mean,-11.359088,3.636294,213.033360,64.444010,0.735474,6.242513,1.078482,8.811811,0.215365,0.035255,...,0.088353,187.212226,0.037146,71.159486,15.950311,5.589386,5.177136,2.259291,6.402902,7.309757
std,373.072147,6.919231,113.673486,43.178686,0.182148,5.352072,0.158591,5.909750,0.746016,0.742100,...,0.159276,248.752510,0.052701,18.556167,11.308697,7.764969,6.595386,3.344124,5.343528,5.477978
min,-7999.000000,-20.700000,-99.900000,-99.900000,0.331000,-0.200000,0.849000,-11.800000,0.000000,0.000000,...,0.000000,0.000000,0.000000,7.261850,0.620583,0.000000,0.006219,0.000000,-0.773633,0.000000
25%,5.200000,-0.800000,133.200000,51.500000,0.606000,1.200000,0.972000,4.600000,0.000000,0.000000,...,0.000000,3.225878,0.000000,64.480745,7.919268,1.299561,1.322910,0.469784,1.415820,2.400000
50%,6.100000,3.100000,215.600000,82.600000,0.714000,4.900000,1.029000,8.400000,0.000000,0.000000,...,0.020140,79.286333,0.006458,79.571125,13.409707,3.496592,3.363310,1.058914,5.084766,6.375000
75%,7.500000,8.600000,325.900000,96.700000,0.847000,11.200000,1.136000,13.200000,0.000000,0.000000,...,0.106016,284.564780,0.060809,83.691862,21.733892,6.673359,6.299936,2.529453,11.600000,12.175000
max,22.100000,27.200000,360.000000,99.700000,1.494000,19.900000,2.017000,32.400000,21.598444,22.397800,...,1.380904,1006.826726,0.322221,84.942103,102.194142,110.256270,137.051147,55.227400,19.400000,22.850000

In [68]:
# What dataset contains
print(raw_data.columns)

Index(['Datetime', 'Vindhastighet Nilsebu', 'Lufttemp. Nilsebu',
       'Vindretning Nilsebu', 'RelHum Nilsebu', 'Vannstand Lyngsåna',
       'Vanntemp. Hiafossen', 'Vannstand Hiafossen', 'Lufttemp Fister',
       'Nedbør Fister', 'Q_Lyngsvatn_overlop', 'Q_tapping',
       'Vannstand Kalltveit', 'Q_Kalltveit', 'Vanntemp. Kalltveit kum',
       'Nedbør Nilsebu', 'Vanntemp. Hiavatn', 'Vannstand Hiavatn',
       'Vanntemp. Musdalsvatn', 'Vannstand Musdalsvatn',
       'Vanntemp. Musdalsvatn nedstrøms', 'Vannstand Musdalsvatn nedstrøms',
       'Vanntemp. Viglesdalsvatn', 'Vannstand Viglesdalsvatn', 'Q_HBV',
       'PRECIP_HBV', 'TEMP_HBV', 'SNOW_MELT_HBV', 'SNOW_SWE_HBV', 'Evap_HBV',
       'SOIL_WAT_HBV', 'GR_WAT_HBV', 'Q_Kalltveit_uten_tapping', 'Q_HBV_mean',
       'Q_Lyngsaana', 'Vanntemp. Lyngsåna', 'Vanntemp. Kalltveit elv'],
      dtype='object')

In [69]:
# Find amount of null values in dataset
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63288 entries, 0 to 63287
Data columns (total 37 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Datetime                         63288 non-null  datetime64[ns]
 1   Vindhastighet Nilsebu            62955 non-null  float64
 2   Lufttemp. Nilsebu                63102 non-null  float64
 3   Vindretning Nilsebu              63079 non-null  float64
 4   RelHum Nilsebu                   63079 non-null  float64
 5   Vannstand Lyngsåna               50380 non-null  float64
 6   Vanntemp. Hiafossen              50192 non-null  float64
 7   Vannstand Hiafossen              50192 non-null  float64
 8   Lufttemp Fister                  63288 non-null  float64
 9   Nedbør Fister                    63288 non-null  float64
 10  Q_Lyngsvatn_overlop              63286 non-null  float64
 11  Q_tapping                        63286 non-null  float64
 12  Vannstand Kalltveit              63274 non-null  float64
 13  Q_Kalltveit                      63288 non-null  float64
 14  Vanntemp. Kalltveit kum          63269 non-null  float64
 15  Nedbør Nilsebu                   63288 non-null  float64
 16  Vanntemp. Hiavatn                45837 non-null  float64
 17  Vannstand Hiavatn                45836 non-null  float64
 18  Vanntemp. Musdalsvatn            45978 non-null  float64
 19  Vannstand Musdalsvatn            45978 non-null  float64
 20  Vanntemp. Musdalsvatn nedstrøms  45955 non-null  float64
 21  Vannstand Musdalsvatn nedstrøms  45955 non-null  float64
 22  Vanntemp. Viglesdalsvatn         45858 non-null  float64
 23  Vannstand Viglesdalsvatn         45858 non-null  float64
 24  Q_HBV                            63288 non-null  float64
 25  PRECIP_HBV                       63288 non-null  float64
 26  TEMP_HBV                         63288 non-null  float64
 27  SNOW_MELT_HBV                    29595 non-null  float64
 28  SNOW_SWE_HBV                     29595 non-null  float64
 29  Evap_HBV                         29595 non-null  float64
 30  SOIL_WAT_HBV                     29595 non-null  float64
 31  GR_WAT_HBV                       29595 non-null  float64
 32  Q_Kalltveit_uten_tapping         63288 non-null  float64
 33  Q_HBV_mean                       31241 non-null  float64
 34  Q_Lyngsaana                      63288 non-null  float64
 35  Vanntemp. Lyngsåna               63283 non-null  float64
 36  Vanntemp. Kalltveit elv          50316 non-null  float64
dtypes: datetime64[ns](1), float64(36)
memory usage: 17.9 MB

In [70]:
inflow_Kalltveit = raw_data[['Q_Kalltveit']]
inflow_Kalltveit.index = raw_data['Datetime']
inflow_Kalltveit.describe()

        Q_Kalltveit
count  63288.000000
mean       6.509245
std        7.565526
min        0.000000
25%        2.683190
50%        4.097010
75%        7.141195
max      110.256270

In [71]:
inflow_Kalltveit_uten_tapping =  raw_data[['Q_Kalltveit_uten_tapping']]
inflow_Kalltveit_uten_tapping.index = raw_data['Datetime']
inflow_Kalltveit_uten_tapping.describe()

       Q_Kalltveit_uten_tapping
count              63288.000000
mean                   5.589386
std                    7.764969
min                    0.000000
25%                    1.299561
50%                    3.496592
75%                    6.673359
max                  110.256270

In [72]:
raw_data.tail(30)

,Datetime,Vindhastighet Nilsebu,Lufttemp. Nilsebu,Vindretning Nilsebu,RelHum Nilsebu,Vannstand Lyngsåna,Vanntemp. Hiafossen,Vannstand Hiafossen,Lufttemp Fister,Nedbør Fister,...,SNOW_MELT_HBV,SNOW_SWE_HBV,Evap_HBV,SOIL_WAT_HBV,GR_WAT_HBV,Q_Kalltveit_uten_tapping,Q_HBV_mean,Q_Lyngsaana,Vanntemp. Lyngsåna,Vanntemp. Kalltveit elv
63258,2022-03-20 18:00:00,7.9,1.9,102.5,43.7,NaN,NaN,NaN,7.6,0.000000,...,0.169220,454.898800,0.002581,84.632722,13.756803,2.162487,2.228524,0.597819,2.108984,3.475
63259,2022-03-20 19:00:00,6.7,1.4,296.6,42.0,NaN,NaN,NaN,8.2,0.000000,...,0.136109,454.751065,0.002062,84.631498,13.745685,2.172259,2.231971,0.588713,1.904297,3.075
63260,2022-03-20 20:00:00,6.4,0.7,346.0,43.5,NaN,NaN,NaN,8.1,0.000000,...,0.091424,454.651831,0.001326,84.630735,13.691096,2.166936,2.226760,0.591183,1.691797,2.800
63261,2022-03-20 21:00:00,14.6,0.1,107.8,58.3,NaN,NaN,NaN,6.9,0.000000,...,0.058766,454.588045,0.000692,84.630405,13.605482,2.185343,2.211974,0.579485,1.486328,2.525
63262,2022-03-20 22:00:00,6.4,0.1,328.4,40.1,NaN,NaN,NaN,6.0,0.000000,...,0.058662,454.524373,0.000694,84.630073,13.521140,2.172441,2.192663,0.580923,1.269141,2.375
63263,2022-03-20 23:00:00,8.1,0.2,170.5,41.8,NaN,NaN,NaN,6.1,0.000000,...,0.063013,454.455977,0.000802,84.629661,13.442405,2.131554,2.173450,0.559914,1.033594,2.275
63264,2022-03-21 00:00:00,8.0,-0.2,44.9,49.0,NaN,NaN,NaN,4.1,0.000000,...,0.045096,454.407029,0.000376,84.629563,13.347434,2.098602,2.139189,0.523529,0.824023,2.125
63265,2022-03-21 01:00:00,6.3,-0.6,106.2,48.5,NaN,NaN,NaN,4.3,0.000000,...,0.031067,454.373308,0.000000,84.629755,13.240284,2.054222,2.108047,0.425647,0.629687,1.950
63266,2022-03-21 02:00:00,10.3,-0.7,105.3,49.4,NaN,NaN,NaN,4.7,0.000000,...,0.027721,454.343219,0.000000,84.629926,13.131572,2.002673,2.068161,0.314453,0.525391,1.825
63267,2022-03-21 03:00:00,8.9,-0.5,104.9,47.7,NaN,NaN,NaN,3.8,0.000000,...,0.034279,454.306012,0.000056,84.630081,13.031012,1.796930,2.022807,0.263165,0.461719,1.650
63268,2022-03-21 04:00:00,8.6,-0.5,54.8,47.4,NaN,NaN,NaN,5.3,0.000000,...,0.034227,454.268861,0.000056,84.630236,12.932010,1.723819,1.860711,0.246635,0.392188,1.550
63269,2022-03-21 05:00:00,8.8,0.0,87.2,47.0,NaN,NaN,NaN,5.5,0.000000,...,0.000000,454.268861,0.000000,84.630236,12.801100,1.656107,1.788919,0.251236,0.361133,1.425
63270,2022-03-21 06:00:00,6.7,0.1,77.9,46.4,NaN,NaN,NaN,6.0,0.000000,...,0.052639,454.211725,0.000702,84.629859,12.723738,1.631824,1.661591,0.254875,0.350391,1.375
63271,2022-03-21 07:00:00,8.9,0.1,60.2,49.3,NaN,NaN,NaN,6.9,0.000000,...,0.057980,454.148792,0.000703,84.629514,12.652848,1.602053,1.651097,0.271108,0.389453,1.325
63272,2022-03-21 08:00:00,9.3,1.3,94.3,47.2,NaN,NaN,NaN,8.1,0.000000,...,0.117281,454.021493,0.002002,84.628239,12.641035,1.551328,1.621129,0.330413,0.451367,1.350
63273,2022-03-21 09:00:00,16.5,1.6,107.4,46.7,NaN,NaN,NaN,8.5,0.000000,...,0.144840,453.864280,0.002335,84.626805,12.656379,1.537894,1.569410,0.910791,0.540234,1.475
63274,2022-03-21 10:00:00,13.9,2.1,107.0,45.7,NaN,NaN,NaN,9.3,0.000000,...,0.177523,453.671593,0.002889,84.625024,12.703450,1.870843,1.563664,1.285916,0.664844,1.875
63275,2022-03-21 11:00:00,14.3,2.2,112.0,45.1,NaN,NaN,NaN,9.0,0.000000,...,0.184575,453.471251,0.003011,84.623171,12.756699,2.497307,1.889881,0.910008,0.847656,2.425
63276,2022-03-21 12:00:00,10.0,1.3,153.4,62.8,NaN,NaN,NaN,9.5,0.000000,...,0.126406,453.334047,0.002033,84.621932,12.752289,2.296237,2.514443,0.629309,1.108203,2.950
63277,2022-03-21 13:00:00,14.7,1.8,110.3,56.0,NaN,NaN,NaN,9.0,0.000000,...,0.158331,453.162191,0.002591,84.620339,12.779173,1.905865,2.402596,0.529734,1.219531,3.450
63278,2022-03-21 14:00:00,13.6,2.2,108.8,49.7,NaN,NaN,NaN,10.3,0.000000,...,0.183682,452.962818,0.003044,84.618457,12.830432,1.758370,2.407556,0.488528,1.250000,3.675
63279,2022-03-21 15:00:00,14.3,1.9,110.9,52.3,NaN,NaN,NaN,9.4,0.000000,...,0.163989,452.784821,0.002723,84.616776,12.861665,1.661648,2.419446,0.468685,1.238281,3.875
63280,2022-03-21 16:00:00,11.5,1.3,114.2,56.5,NaN,NaN,NaN,9.0,0.000000,...,0.125162,452.648967,0.002063,84.615509,12.854492,1.607379,2.424852,0.478452,1.355859,3.875
63281,2022-03-21 17:00:00,13.1,1.3,115.0,53.0,NaN,NaN,NaN,8.2,0.000000,...,0.124894,452.513404,0.002070,84.614236,12.847195,1.620139,2.417037,0.462089,1.421094,3.700
63282,2022-03-21 18:00:00,12.1,0.7,109.2,54.7,NaN,NaN,NaN,7.6,0.000000,...,0.087646,452.418271,0.001403,84.613393,12.803645,1.574180,2.410818,0.466970,1.375781,3.400
63283,2022-03-21 19:00:00,11.3,-1.0,106.3,84.7,NaN,NaN,NaN,6.7,0.000000,...,0.016940,452.399884,0.000000,84.613501,12.691728,1.572981,2.401503,0.464860,1.323438,3.100
63284,2022-03-21 20:00:00,11.7,-0.4,105.8,84.7,NaN,NaN,NaN,5.7,0.000000,...,0.035770,452.361058,0.000171,84.613558,12.600009,1.556832,2.366949,0.451835,1.264649,2.825
63285,2022-03-21 21:00:00,9.5,0.4,143.2,80.8,NaN,NaN,NaN,6.3,0.000000,...,0.068025,452.287223,0.001072,84.612921,12.541249,1.541402,2.341590,0.450595,1.244922,2.625
63286,2022-03-21 22:00:00,8.7,0.5,145.8,78.0,NaN,NaN,NaN,5.2,1.099694,...,0.074288,452.206589,0.001187,84.612209,12.489559,1.526564,2.324290,0.433061,1.252735,2.575
63287,2022-03-21 23:00:00,8.4,0.2,152.5,85.3,NaN,NaN,NaN,3.3,1.299944,...,0.059800,452.141680,0.000850,84.611742,12.424557,1.505963,2.308757,0.439196,1.230469,2.500

In [76]:
from sklearn.model_selection import train_test_split

train, temp = train_test_split(inflow_Kalltveit, train_size=0.7, shuffle=False)
val, test = train_test_split(temp, test_size=0.3, shuffle=False)

print(train.shape, val.shape, test.shape)

(44301, 1) (13290, 1) (5697, 1)

                     Q_Kalltveit
Datetime
2015-01-01 00:00:00      3.37060
2015-01-01 01:00:00      3.45242
2015-01-01 02:00:00      3.56260
2015-01-01 03:00:00      3.74423
2015-01-01 04:00:00      4.02901
...                          ...
2020-01-20 16:00:00      7.14669
2020-01-20 17:00:00      7.45883
2020-01-20 18:00:00      7.81983
2020-01-20 19:00:00      8.26822
2020-01-20 20:00:00      8.78916

[44301 rows x 1 columns]

In [74]:
train.to_csv(r'../data/clean_data/univariate_Q_Kallveit/train.csv')
val.to_csv(r'../data/clean_data/univariate_Q_Kallveit/val.csv')
test.to_csv(r'../data/clean_data/univariate_Q_Kallveit/test.csv')